#!/bin/bash -e

cd $(dirname $0)/..
(
  set -x
  pdflatex -interaction=nonstopmode -halt-on-error *.tex
)

# TODO: rename main.tex then remove this line
mv main.pdf solana-whitepaper.pdf

if [[ -n "$BUILDKITE_TAG" ]]; then
  if ! which wget; then
    if [[ "$BUILDKITE" = "true" ]]; then
      # The "blang/latex:ubuntu" image is missing wget, install it manually for
      # now to avoid having to maintain a custom docker image
      echo --- Installing wget
      apt-get update
      apt-get install -y wget
    else
      echo Warning: wget not found
    fi
  fi

  echo --- Uploading assets for $BUILDKITE_TAG
  ci/upload-release-asset.sh solana-labs whitepaper \"$BUILDKITE_TAG\" \
    solana-whitepaper.pdf
fi

exit 0
