#!/bin/bash -e

cd $(dirname $0)/..
(
  set -x
  pdflatex -interaction=nonstopmode -halt-on-error *.tex
)

# TODO: rename main.tex then remove this line
mv main.pdf solana-whitepaper.pdf

if [[ -n "$BUILDKITE_TAG" ]]; then
  if [[ "$BUILDKITE" = "true" ]]; then
    echo --- Installing additional packages
    # The "blang/latex:ubuntu" image is missing some tools, install them
    # manually for now to avoid having to maintain a custom docker image
    apt-get update
    for package in wget bzip2; do
      apt-get install -y $package
    done
  fi

  echo --- Uploading assets for $BUILDKITE_TAG
  ci/upload-release-asset.sh solana-labs whitepaper \"$BUILDKITE_TAG\" \
    solana-whitepaper.pdf
fi

exit 0
